### ISSUE TITLE
Port to other Minecraft plugin APIs such as Sponge

### ISSUE THREAD

**Issue by zhuowei** [zhuowei/RaspberryJuice#17]
with the status of Bukkit uncertain, it might be a good idea to look into porting for other APIs.

Sponge is a new client/server plugin-style API under development:

https://github.com/SpongePowered/SpongeAPI

They're at a very early stage though.

Forge is a fairly established API - would that be a bit too low-level?

Any other Minecraft server APIs that we can target, ideally ones that are already used in education?

**Comment by martinohanlon** [comment]
@zhuowei A port of raspberry juice has now been done to forge... Your plugin is spreading!

**Comment by Red5d** [comment]
The current Bukkit plugin works on Spigot too.

**Comment by martinohanlon** [comment]
I thought you would be interested in knowing there is now an Android version https://play.google.com/store/apps/details?id=mobi.omegacentauri.rjm&hl=en

**Comment by r0bis** [comment]
Hi Martin; I am trying to set my kids working on Python by the book "Adventures in Minecraft". I have set up server on an opensuse server on LAN and spigot builds created with their BuildTools.jar run fine on it. Where I fall down is enabling Python access to server. RaspberryJuice plugin is loaded, but the commands that I managed run are chat commands only; block commands throw exceptions. I guess this is due to craftbukkit server versions I tested - 1.8.3 and 1.9.2. I was wondering - if my children learned to build something with programming in version 1.6.4 - could they open that world with 1.9.2 server later? And the second question - what would be the newest servers (like canary?) that would support python access via something like raspberryjuice? Thanks. Rob

**Comment by martinohanlon** [comment]
@r0bis I have just released a new version of RaspberryJuice that supports Minecraft 1.9.+ . Certain APIs calls that I was using were removed/changed in 1.9 and I had to do an update.

**Comment by r0bis** [comment]
@martinohanlon Thanks Martin, that is very good news.

**Comment by martinohanlon** [comment]
Closing. Spigot / bukkit builds are stable.
