### ISSUE TITLE
Compatibility issue

### ISSUE THREAD

**Issue by arpruss** [zhuowei/RaspberryJuice#34]
I noticed that the player.*() API in the included version of mcpi/minecraft.py sends an extra None argument at the beginning of argument lists. For instance, mc.player.getTilePos(10,10,10) would send player.getTilePos(None,10,10,10). I believe (correctly?) that the official MC PI interface doesn't allow the extra None argument, nor do some of the other implementations of the API (like my RaspberryJam for Desktop, Android and Minetest).

**Comment by martinohanlon** [comment]
Is this the mod made a while ago by @jclaggett before I really got involved so that a named player could be passed into the player functions?  https://github.com/zhuowei/RaspberryJuice/commit/5f13df9bc22ed8caee080fae32d929b57d019e88

He made it so that he could support multiplayer coding.  This was done at a time before RaspberryJuice supported entities and is redundant in some respects now. I have considered removing it before.

@jclaggett any objection to me tidying this up next time we do a change?

**Comment by martinohanlon** [comment]
I've removed it from the python libraries, at some point I'll tidy up the code and remove it from the plugin too.

**Comment by martinohanlon** [comment]
removed from raspberryjuice plugin
