### ISSUE TITLE
Add /py command

### ISSUE THREAD

**Issue by neuhaus** [zhuowei/RaspberryJuice#63]
The [raspberry jam mod](https://github.com/arpruss/raspberryjammod) has a very useful "/py" command that lets you execute python scripts in the server's "mcpipy" directory directly from within minecraft.

Feature request: Add this command to Raspberry Juice!

**Comment by martinohanlon** [comment]
I see the benefit of this functionality but I dont like the idea of adding the /py command to RaspberryJuice, mainly because it could (and should) be considered a significant security issue. It effectively allows you to execute code on the server. Not good!

This could result in RaspberryJuice being marked as an 'abnormal' plugin, something I would like to avoid.

There are other plugins which allow you to execute a python script (see https://dev.bukkit.org/projects/pydevtools), perhaps using this plugin in addition to RaspberryJuice fulfills your need?

If not, perhaps we could create a seperate simple plugin which does the same thing as jam mod's /py.
