### ISSUE TITLE
Is this repo still active?

### ISSUE THREAD

**Issue by eschwartz** [zhuowei/RaspberryJuice#83]
I've been poking around this repo, trying to wrap my head around minecraft modding/scripting. The RasberryJuice/mcpi setup is really neat. I'm hoping to be able to use Minecraft as an entrypoint to  teach my kids to code in python, and this stack has a lot of potential.

I'm just wondering if this repo is being actively maintained -- if I look to expand/refactor, will I be able to get a PR through? I notice there are a number of promising looking PRs open, including a [major v1.14 refactor](https://github.com/zhuowei/RaspberryJuice/pull/82). 

@zhuowei -- are you open to adding more contributors to the project? Should I fork and go my own direction? I also noticed [some talk of moving off of bukkit](https://github.com/zhuowei/RaspberryJuice/issues/17) -- is there another plugin I should working with instead?

Thanks!

**Comment by martinohanlon** [comment]
I am still maintaining the project. I have been away for a while, but in the next few weeks will be picking up a new version and the PRs.

**Comment by wensheng** [comment]
[JuicyRaspberryPie](https://github.com/wensheng/JuicyRaspberryPie) is current and support minecraft 1.14.4.  It's initially based off RaspberryJuice, but now can be considered a superset of it.  

Right now because of Minecraft change from 1.13, the API is not compatible with minecraft Pi anymore. Mainly numeric ID was replaced by namespaced name, like "gold_block" or "minecraft:stone".

JuicyRaspberryPie has both Spigot/bukkit version and a Forge version.

If you're interested, please take a look, I'm the author, I'm trying to finish doc and work out a few bugs.  Contributions are welcome.

**Comment by eschwartz** [comment]
cool, thanks for the info!
